#!/usr/bin/env groovy

pipeline {
    agent none
    stages {
		stage('Confirmation') {
            steps {
				timeout(time: 60, unit: 'SECONDS') {
				input(message: 'Confirm Deployement to UAT env', ok: 'Approve')
				}
            }
        }
        stage('Deploy') {
			agent any
            steps {
                sh """ git branch """
            }
        }
    }
}
