#!/usr/bin/env groovy

pipeline {
    agent none
    stages {
		stage('Confirmation') {

			timeout(time: 60, unit: 'SECONDS') {
				 input(message: 'Confirm Deployement to QA env', ok: 'Approve')
			}
        }
        stage('Deploy') {
			agent any
            steps {
                sh """ git branch """
            }
        }
    }
}
